### ISSUE TITLE
Web RTC on Safari

### ISSUE THREAD

**Issue by Badpookey** [webrtcftw/iswebrtcreadyyet.com#102]
Safari now supports WebRTC, your scorecard needs updating

**Comment by fippo** [comment]
I don't think they deserve green while ignoring a MUST strength requirement for VP8 as a video codec.

**Comment by Badpookey** [comment]
Nonetheless, I've been able to run a number of applications. The scorecard suggests its completely unusable

**Comment by fippo** [comment]
the score card is outdated (and even deprecated). If you want to see stuff that works check https://webrtc.github.io/samples/

**Comment by xdumaine** [comment]
@Badpookey The scorecard has it on yellow, not red. Red's always been "unsupported" while yellow is "partially complete." So it is accurate as is.

**Comment by lgrahl** [comment]
> I don't think they deserve green while ignoring a MUST strength requirement for VP8 as a video codec.

@fippo Digging up old issues here... but for the same reason, Edge should be red, too. Without data channels, they don't even deserve a yellow. 😉

**Comment by fippo** [comment]
Edge doesn't consciously ignore datachannels for political reasons while Safari does.
