### ISSUE TITLE
Typo "dogfood" on scorecard page

### ISSUE THREAD

**Issue by nathanbabcock** [webrtcftw/iswebrtcreadyyet.com#105]
On this page: http://iswebrtcreadyyet.com/legacy.html

Under the Talky sidebar:

> Teams at Mozilla and Google are actively using Talky to **dogfood** and improve their WebRTC implementations.

**Comment by xdumaine** [comment]
That's not a typo - https://en.wikipedia.org/wiki/Eating_your_own_dog_food
