### ISSUE TITLE
Opera is starting to turn on getUserMedia, investigate an update chart accordingly.

### ISSUE THREAD

**Issue by HenrikJoreteg** [webrtcftw/iswebrtcreadyyet.com#11]

**Comment by fippo** [comment]
When they first added this a couple of months ago, "opera next" was recognized as chrome by adapter.js. So this is probably a matter of figuring out when to copy the "chrome" column to the opera column.

Besides, I think the table is incorrect, opera has supported getUserMedia for quite a long time.

**Comment by HenrikJoreteg** [comment]
Hi @fippo, I think they had it "on" before switching to webkit. But, navigator.getUserMedia doesn't even exist in current Opera. At least didn't when I first made the table.

**Comment by niutech** [comment]
I can confirm that Opera 18 supports both `window.getUserMedia` and `window.RTCPeerConnection` so please update the table.

**Comment by latentflip** [comment]
Hey @niutech the current stable release is opera 17, but since we have FF nightly and chrome canary on there we should probably add Opera Next (18) too.

**Comment by brucelawson** [comment]
Opera 18 (released today) hs gUM and window.RTCPeerConnection: http://my.opera.com/ODIN/blog/opera-desktop-18-released

**Comment by latentflip** [comment]
Thanks Bruce, I'll get it checked off and updated.

**Comment by latentflip** [comment]
Fixed, thanks Bruce.

**Comment by brucelawson** [comment]
no, thank _you_
