### ISSUE TITLE
Echo cancellation in Chrome Canary

### ISSUE THREAD

**Issue by samdutton** [webrtcftw/iswebrtcreadyyet.com#17]
Working pretty well, so maybe could be a yellow?

**Comment by HenrikJoreteg** [comment]
Indeed, those should be yellow, I’d say even for Chrome 31. Possibly even green for Canary?

**Comment by fippo** [comment]
@samdutton: is a special constraint needed like for the IPv6 support that landed last week or is it enabled by default? ISTR there was one, but don't seem to have anything starred in the issue tracker.

**Comment by samdutton** [comment]
Yes: enabled by default.
