### ISSUE TITLE
Order table based on support

### ISSUE THREAD

**Issue by cyberixae** [webrtcftw/iswebrtcreadyyet.com#27]
I am not sure what the order of lines and columns is currently based on. However, I think it would make sense to have the standard with most support to be the first line and the browser that supports most standards to be the left most browser. If it was like that you would know with one glance which standards and browsers you might want to use today.

**Comment by cyberixae** [comment]
![inorder](https://cloud.githubusercontent.com/assets/1158275/4432112/faab5f98-4685-11e4-9f1f-4689b25084e8.png)

**Comment by adamavenir** [comment]
@cyberixae Sounds good to me. 

Would you mind submitting a pull request reordering these columns in this way?

**Comment by cyberixae** [comment]
PR created!

**Comment by fippo** [comment]
people seem to like the new layout -- saw it twice on twitter today. Thanks!
