### ISSUE TITLE
Support for StatsAPI()

### ISSUE THREAD

**Issue by vr000m** [webrtcftw/iswebrtcreadyyet.com#33]
=)

**Comment by fippo** [comment]
yellow for everyone? Or do we punish chrome for not having fixed http://code.google.com/p/webrtc/issues/detail?id=2031 :-)

**Comment by vr000m** [comment]
you could refer to http://w3c.github.io/webrtc-stats/webrtc-stats, but yeah could we have shades of yellow?!
