### ISSUE TITLE
Move to webrtcftw org

### ISSUE THREAD

**Issue by adamavenir** [webrtcftw/iswebrtcreadyyet.com#35]
I think we should move iswebrtcreadyyet.com to the webrtcftw org, given this is entirely in line with that group's goals. :)

**Comment by HenrikJoreteg** [comment]
wfm

**Comment by adamavenir** [comment]
@bear @fippo @stpeter @legastero @fritzy — what do you think? :)

**Comment by bear** [comment]
+1

**Comment by fritzy** [comment]
Good idea

**Comment by adamavenir** [comment]
Well then! Let's do it! :)

**Comment by stpeter** [comment]
+1 here too

**Comment by bear** [comment]
done

**Comment by adamavenir** [comment]
@bear? :) the suggestion was webrtcftw not otalk

<3

**Comment by fippo** [comment]
erm... I don't think that is a good idea because iswebrtcreadyyet.com is an "established brand" already, i.e. people use it in their slides.

**Comment by fippo** [comment]
ah... you just meant move the repo to the github org? +1

**Comment by bear** [comment]
doh! - fixed
