### ISSUE TITLE
Opera data incorrect?

### ISSUE THREAD

**Issue by miketaylr** [webrtcftw/iswebrtcreadyyet.com#4]
Opera 17 is based on Chromium so support should basically mirror Canary... is your test data from Opera 12 (which supported other parts like getUserMedia)?

**Comment by fippo** [comment]
right, opera next is basically equivalent to chrome, including prefixes.

**Comment by miketaylr** [comment]
Current Opera stable is too (since 15).

**Comment by latentflip** [comment]
It looks like at present the getUserMedia and RTCPeerConnection's are not hooked up yet in opera: http://caniuse.com/stream and http://caniuse.com/rtcpeerconnection

It looks like getUserMedia may be supported in Opera 18, less sure about RTCPeerConnection though.

**Comment by HenrikJoreteg** [comment]
leaving those red was based entirely on actual attempts. For example, when I run Opera 16.0.1196.14 (which was latest at the time the site was made) and I look for `navigator.webkitGetUserMedia` it's not there. Same with `webkitRTCPeerConnection` so yeah... it's built on chromium. But the stuff just isn't there as far as I can tell. 

If I'm wrong, please re-open this.
