### ISSUE TITLE
Firefox TURN support

### ISSUE THREAD

**Issue by matthewrobertson** [webrtcftw/iswebrtcreadyyet.com#5]
I am not sure that Firefox stable (v24) actually supports TURN. I know they claim that it is working but I tested today using apprtc and a firewalled network and could only get the nightly (aurora) to work. 

Also, Firefox definitely does not support TURN TCP. I have found that, the only way to reliably form a peer connection between users in the wild is using TCP over port 443 or 80, thus TURN support without TURN TCP is really incomplete and I think the box should be yellow in your support matrix.

**Comment by bear** [comment]
i'll make a note to check with the team to see how this box is tested and get back to ya. 

Thanks for the extra detail and help!

**Comment by fippo** [comment]
old thread alert -- I just saw this because FF30 actually fixed a bug which prevented TURN from working at all on windows.

TURN/TCP is also working reasonably well AFAIK.
