### ISSUE TITLE
What voice codecs are supported in WebRTC

### ISSUE THREAD

**Issue by booksunt** [webrtcftw/iswebrtcreadyyet.com#69]
What voice codecs are supported in WebRTC

**Comment by fippo** [comment]
For interoperability, Opus and G.711 are mandatory to implement. Browsers do support other codecs like G.722, ISAC and Silk.

btw, the [discuss-webrtc mailing list](https://groups.google.com/forum/#!forum/discuss-webrtc) may be a better venue for asking questions.
