### ISSUE TITLE
MediaRecorder support

### ISSUE THREAD

**Issue by d2vid** [webrtcftw/iswebrtcreadyyet.com#76]
Firefox and Chrome (canary and now stable, as of this week) support the WebRTC MediaRecorder integration:

[Chrome support](https://www.chromestatus.com/feature/5929649028726784)
[Firefox support](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder)

Could you add a column to the grid labeled "MediaRecorder" integration? I think it would be useful to quite a few WebRTC followers.

What do you think?

**Comment by fippo** [comment]
+1 -- can you make a pull request? (just add it to the HTML)
