### ISSUE TITLE
Add VP9

### ISSUE THREAD

**Issue by k3rmitt** [webrtcftw/iswebrtcreadyyet.com#78]
google added support for VP9, should be part of the list

**Comment by fippo** [comment]
this was removed in the past since VP9 is not a mandatory to implement codec. See https://github.com/webrtcftw/iswebrtcreadyyet.com/pull/42

**Comment by Charwinger21** [comment]
While VP9 is not required, it became an [official optional part of the standard](https://developers.google.com/web/updates/2016/01/vp9-webrtc) earlier this year, and is supported natively by every major browser except for Safari (which does not appear to support WebRTC at all at the moment).

It may need to be in an "optional" section (possibly even below the fold), however with it being such a widespread option, it really should be included.
