### ISSUE TITLE
Internet Explorer ist missing

### ISSUE THREAD

**Issue by awittli** [webrtcftw/iswebrtcreadyyet.com#81]
one of the market leader is missing: Internet Explorer 11 (other are out of support)
[I know it is not support anything, but it shows real life and MS interests

**Comment by xdumaine** [comment]
Internet explorer 11 doesn't support WebRTC. Microsoft Edge (the successor to IE) is on the list, as the first microsoft browser with WebRTC (actually ORTC) support.
