### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by miketaylr** [webrtcftw/iswebrtcreadyyet.com#9]
According to iswebrtcreadyyet.com, "This site is open source on Github" but I was hoping you could clarify license information in the README (or add a license file to the repo). I love what you guys have done here and I'd like to use it as a base for some web compatibility tracking stuff, but would feel better if I knew that the CSS, etc. allowed derived works.

Thanks!

**Comment by latentflip** [comment]
Hi Mike,

We'll get a license added, which I am 99% sure will be MIT.

Sorry for not making it clearer.

**Comment by miketaylr** [comment]
Thanks @latentflip!

**Comment by latentflip** [comment]
H Mike,

We went for a [Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported](http://creativecommons.org/licenses/by-nc-sa/3.0/deed.en_US) and have added it to the README.md.

Thanks!

**Comment by miketaylr** [comment]
Perfect, thanks!
