### ISSUE TITLE
domain expired: iswebrtcreadyyet.com

### ISSUE THREAD

**Issue by squash** [webrtcftw/iswebrtcreadyyet.com#91]
Site is unavailable as the domain has expired.

**Comment by samdutton** [comment]
😰 

iswebrtcready.net and .info are available.

**Comment by adamavenir** [comment]
😬 So sorry. Oversight on my end. 

Thought it was set to auto-renew. We're renewing it.

**Comment by adamavenir** [comment]
It's been renewed but will probably take a bit for it to show back up.

iswebrtcreadyyetdotcomreadyyet.com

**Comment by samdutton** [comment]
Yay!

**Comment by adamavenir** [comment]
Closing. I can confirm it's back up for me. @squash thank you so much for opening this. @fippo thanks for flagging me down.

**Comment by fippo** [comment]
@wraithgar: can you show mr. brault a picture of a real flag?
